#pragma config(Sensor, S1,     DIMU,           sensorI2CCustomFastSkipStates)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: dexterind-imu-test1.c 123 2012-11-02 16:35:15Z xander $
 */

/**
 * dexterind-imu.h provides an API for the Dexter Industries IMU Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to Dexter Industries for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.54 AND HIGHER.
 * Xander Soldaat (xander_at_botbench.com)
 * 07 August 2011
 * version 0.1
 */

#include "drivers/dexterind-imu.h"
task main(){

  float z_val, heading;      // Gyro axis values
	heading = 0;
	z_val = 0;
	int counts = 0;
  eraseDisplay();
	if (!DIMUconfigAccel(DIMU, DIMU_ACC_RANGE_2G))
    PlaySound(soundException);
	if(!DIMUconfigGyro(DIMU, DIMU_GYRO_RANGE_500))
    PlaySound(soundException);

  time1[T1] = 0;

  while(true){
  	while(time1[T1] <10)
  		wait1Msec(1);
  	time1[T1] = 0;
  	z_val = -1.68*DIMUreadGyroAxis(DIMU, DIMU_GYRO_Z_AXIS);
  	if ( ( z_val < 1 ) && ( z_val > 0 ) ){
  		heading += 0;
  		counts = counts + 1;
  		if (counts > 5){
  			if ( heading <= 4 ){;
  				heading = 0;
  			}
  			counts = 0;
  		}
  	}else{
  		heading += ( z_val / 2 ) * 0.01;
  	}
  	nxtDisplayTextLine(2, "%2.0f", heading);
  	nxtDisplayTextLine(3, "%f", z_val);
  	nxtDisplayTextLine(4, "%2.0f", counts);
  }

  // Fire up the gyro and initialize it. Only needs to be done once.
  //DIMUconfigGyro(DIMU, DIMU_GYRO_RANGE_500);

  //while (true){

  //  DIMUreadGyroAxes(DIMU, x_val, y_val, z_val);

  //	z_val = -1.68*DIMUreadGyroAxis(DIMU, DIMU_GYRO_Z_AXIS);

	//	nxtDisplayTextLine(2, "%2.0f", z_val);
	//	wait1Msec(50);
  }


/*
 * $Id: dexterind-imu-test1.c 123 2012-11-02 16:35:15Z xander $
 */
