#pragma config(Sensor, S1,     HTMSSUMO,            sensorLightActive)
#pragma config(Motor,  motorA,          RIGHT,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: mindsensors-sumoeyes-test1.c 123 2012-11-02 16:35:15Z xander $
 */

/**
 * mindsensors-sumoeyes.h provides an API for the Mindsensors Sumo Eyes Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.54 AND HIGHER.
 * Xander Soldaat (xander_at_botbench.com)
 * 20 February 2011
 * version 0.4
 */

#include "drivers/mindsensors-sumoeyes.h"

 /*
  =============================================================================
  main task with some testing code

 */

void turnRight();
void turnLeft();
void allStop();
void allGo();
tObstacleZone zone = 0;
task main() {
  // Standard range is set to short range
  bool shortrange = true;

//  tObstacleZone zone2 = 0;
  nNxtButtonTask  = -2;

  eraseDisplay();

  nxtDisplayCenteredTextLine(0, "Mindsensors");
  nxtDisplayCenteredBigTextLine(1, "SUMO Eyes");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Press enter to");
  nxtDisplayCenteredTextLine(6, "switch between");
  nxtDisplayCenteredTextLine(7, "ranges");
  wait1Msec(2000);
  eraseDisplay();

  // Set the sensor to short range
  MSSUMOsetShortRange(HTMSSUMO);

  while(true) {



  /*
  	if (time1[T1] > 1000) {
      if (shortrange == false) {
        // set the sensor to short range and display this
        MSSUMOsetShortRange(HTMSSUMO);
        nxtDisplayClearTextLine(1);
        nxtDisplayTextLine(1, "Short range");
        shortrange = true;
      } else {
        // set the sensor to long range and display this
        MSSUMOsetLongRange(HTMSSUMO);
        nxtDisplayClearTextLine(1);
        nxtDisplayTextLine(1, "Long range");
        shortrange = false;
      }
	    PlaySound(soundBeepBeep);
	    while(bSoundActive)
      time1[T1] = 0;
    }
	*/
    while(nNxtButtonPressed != kEnterButton) {
      // Read the zone data
      zone = MSSUMOreadZone(HTMSSUMO);

	    switch (zone) {
	      case MSSUMO_FRONT: allStop(); nxtDisplayCenteredBigTextLine(4, "FRONT"); break;
	      case MSSUMO_LEFT:  turnRight(); nxtDisplayCenteredBigTextLine(4, "LEFT");  break;
	      case MSSUMO_RIGHT: turnLeft(); nxtDisplayCenteredBigTextLine(4, "RIGHT"); break;
	      case MSSUMO_NONE:  allGo(); nxtDisplayCenteredBigTextLine(4, "NONE");  break;
	    }
      wait1Msec(50);
    }
  }
}

void turnRight(){
	motor[RIGHT] = 50;
	motor[LEFT] = 25;
	}
void turnLeft(){
	motor[RIGHT] = 25;
	motor[LEFT] = 50;
	}
void allStop(){
	int blockLeft = 0;
	int blockRight = 0;
	motor[RIGHT] = 50;
	motor[LEFT] = -50;
	wait1Msec(750);
  zone = MSSUMOreadZone(HTMSSUMO);
	switch(zone){
		case MSSUMO_LEFT:  blockLeft = 1;  break;
    case MSSUMO_RIGHT: blockRight = 1; break;
    }
	motor[RIGHT] = -50;
	motor[LEFT] = 50;
	wait1Msec(750);
  motor[RIGHT] = -50;
	motor[LEFT] = 50;
	wait1Msec(750);
  zone = MSSUMOreadZone(HTMSSUMO);
	switch(zone){
		case MSSUMO_LEFT:  blockLeft = 1;  break;
    case MSSUMO_RIGHT: blockRight = 1; break;
    }
  if ( ( blockLeft==1 ) && ( blockRight==1 ) ){
  motor[RIGHT] = -50;
	motor[LEFT] = 50;
	wait1Msec(1400);
	} else if ( ( blockLeft==0 ) && ( blockRight==1 ) ){
  motor[RIGHT] = 50;
	motor[LEFT] = -50;
	wait1Msec(750);
	} else if ( ( blockLeft==1 ) && ( blockRight==0 ) ){
  motor[RIGHT] = -50;
	motor[LEFT] = 50;
	wait1Msec(750);
	}
}
void allGo(){
	motor[RIGHT] = 50;
	motor[LEFT] = 50;
	}

/*
 * $Id: mindsensors-sumoeyes-test1.c 123 2012-11-02 16:35:15Z xander $
 */
