#pragma config(Sensor, S1,     DGPS,                sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: DGPS-test1.c 36 2010-11-11 10:20:54Z xander $
 */

/**
 * DGPS-driver.h provides an API for the Dexter Industries GPS Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to Dexter Industries for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 2.00 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 30 October 2010
 * version 0.1
 */

#include "drivers/common.h"
#include "drivers/DGPS-driver.h"

const string sFileName = "testFile.dat";
const int kMaxFileSize = 5000;

long longitude = 0;
long latitude = 0;
long utc = 0;
long longitude2 = 1;
long latitude2 = 1;
bool linkstatus = false;
//int i = 0;


TFileHandle hFileWriteHandle = NOT_A_HANDLE;

bool bFirstNumberOnLine      = true;
TFileIOResult nIoResult      = ioRsltSuccess;

bool bOpenWriteTextFile(const string &sFileName, int nFileSize)
{
	bFirstNumberOnLine = true;
	Delete(sFileName, nIoResult);
	OpenWrite(hFileWriteHandle, nIoResult, sFileName, nFileSize);
	return nIoResult == ioRsltSuccess;
}

void closeWriteTextFile()
{
	Close(hFileWriteHandle, nIoResult);
	hFileWriteHandle = NOT_A_HANDLE;
}

void writeNewLine()
{
	WriteText(hFileWriteHandle, nIoResult, "\r\n");
	bFirstNumberOnLine = true;
	return;
}

void writeDelimiterBetweenNumbers()
{
	if (bFirstNumberOnLine)
		bFirstNumberOnLine = false;
	else
		WriteText(hFileWriteHandle, nIoResult, ", ");
	return;
}

void writeIntegerNumber(long nNumber)
{
	string sTemp;
	writeDelimiterBetweenNumbers();
	//
	// Modify format code ("%d") if you want to change the format -- say to line up the
	// columns for your application; e.g. "%5d" will make every number five characters.
	//
	StringFormat(sTemp, "%d", (long) nNumber);
	WriteText(hFileWriteHandle, nIoResult, sTemp);
	return;
}

task main () {

  nxtDisplayCenteredTextLine(0, "Dexter Ind.");
  nxtDisplayCenteredBigTextLine(1, "GPS");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect sensor");
  nxtDisplayCenteredTextLine(6, "to S1");
  wait1Msec(2000);
  eraseDisplay();

  bOpenWriteTextFile(sFileName, kMaxFileSize);

  while (true) {
//    while (i < 20) {
      // Read the sensor's data
      wait1Msec(10000);
      utc = DGPSreadUTC(DGPS);
      longitude = DGPSreadLongitude(DGPS);
      latitude = DGPSreadLatitude(DGPS);
      linkstatus = DGPSreadStatus(DGPS);

      nxtDisplayCenteredTextLine(0, "DGPS Test 1");
      nxtDrawLine(0, 52, 99, 52);
      nxtDisplayTextLine(2, "UTC: %d", utc);
      nxtDisplayTextLine(3, "Lon: %d", longitude);
      nxtDisplayTextLine(4, "Lat: %d", latitude);
      if (latitude == latitude2 && longitude == longitude2) {
        //do nothing
      }
      else {
        if (linkstatus) {
          writeIntegerNumber(utc);
          writeIntegerNumber(longitude);
         // writeDelimiterBetweenNumbers();
          writeIntegerNumber(latitude);
          writeNewLine();
         // i = i + 1;
          longitude2 = longitude;
          latitude2 = latitude;
          nxtDisplayTextLine(7, "Link Stat: [UP]");
        }
        else {
          nxtDisplayTextLine(7, "Link Stat: [DOWN]");
          nxtDrawLine(0, 20, 99, 20);
          wait1Msec(500);
        }
      }
    }
    closeWriteTextFile();
    StopAllTasks();
//  }
}

/*
 * $Id: DGPS-test1.c 36 2010-11-11 10:20:54Z xander $
 */
