#pragma config(Sensor, S1,     HTMSSUMO,       sensorLightActive)
#pragma config(Sensor, S2,     us_old,         sensorSONAR)
#pragma config(Sensor, S3,     us_new,         sensorSONAR)
#pragma config(Sensor, S4,     DIMU,           sensorI2CCustomFastSkipStates)
#pragma config(Motor,  motorA,          RIGHT,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          CENTER,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/mindsensors-sumoeyes.h"
#include "drivers/dexterind-compass.h"
#include "sensorConfig/US_NEW.h"
#include "sensorConfig/US_OLD.h"
#include "drivers/dexterind-imu.h"
#include "sensorConfig/pollAxies.h"
#include "sensorConfig/readArduino.h"
void runSensors();
void stopSensors();
void turnRight();
void turnHardRight();
void turnLeft();
void turnHardLeft();
void allStall();
void allGo();
void allBack();
void allStop();
void sonarObsticalCheck(int inType);
void SetRawSate();
void makeConnection();
void checkBTLinkConnected();
void testNXshieldSensors();
void testSonar();
tObstacleZone zone = 0;
task main() {
	makeConnection();
	checkBTLinkConnected();
	SetRawSate();
	StartTask(readArduino);
	//StartTask(USNEW);
	StartTask(USOLD);
	StartTask(pAxies);
	MSSUMOsetShortRange(HTMSSUMO);


	while (nNxtButtonPressed != 3) {
		nxtDisplayTextLine(4,"Waiting");
	}
	wait1Msec(2000);
	PlaySound(soundException);

	while(true)

  	{
			runSensors();
  		nxtDisplayCenteredTextLine(1, "Touch 01: %d", touch01);
  		nxtDisplayCenteredTextLine(2, "Touch 02: %d", touch02);

  		//nxtDisplayCenteredBigTextLine(3, "%d", sonar01);

  		nxtDisplayCenteredTextLine(3, "Sonar 01: %d", sonar01);
  		nxtDisplayCenteredTextLine(4, "zA: %d", zA);
  		nxtDisplayCenteredTextLine(5, "xA: %d", xA);
  		nxtDisplayCenteredTextLine(6, "yA: %d", yA);
			zone = MSSUMOreadZone(HTMSSUMO);

	    switch (zone)
	    	{
		      case MSSUMO_FRONT:
		      	allStop();
		      	break;
		      case MSSUMO_LEFT:
		      	turnLeft();
		      	break;
		      case MSSUMO_RIGHT:
		      	turnRight();
		      	break;
		      case MSSUMO_NONE:
		      	allGo();
		      	break;
	    	}
			testNXshieldSensors();


	  	if ( ( us_OldResult < 20 ) || ( ( sonar01 < 20 ) && ( sonar01 > 0 ) ) )
	   		{
	  			sonarObsticalCheck(1);
	  		}


			if ( ( yA > 15 ) || ( yA < -15 ) )
	  		{
		  		allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(750);
					sonarObsticalCheck(3);
					zA=0;xA=0;yA=0;
	  		}
	  	if ( ( xA > 15 ) || ( xA < -15 ) )
	  		{
		  		allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(750);
					sonarObsticalCheck(3);
					zA=0;xA=0;yA=0;
	  		}

  	}

}

void runSensors()
	{
		motor[CENTER] = 40;
	}
void stopSensors()
	{
		motor[CENTER] = 0;
	}
void allGo()
	{
		motor[RIGHT] = 20;
		motor[LEFT] = 20;
	}
void allBack()
	{
		motor[RIGHT] = -20;
		motor[LEFT] = -20;
	}
void allStall()
	{
		motor[RIGHT] = 0;
		motor[LEFT] = 0;
	}
void turnRight()
	{
		motor[RIGHT] = 15;
		motor[LEFT] = 35;
	}
void turnLeft()
	{
		motor[RIGHT] = 35;
		motor[LEFT] = 15;
	}
void turnHardRight()
	{
		motor[RIGHT] = -20;
		motor[LEFT] = 20;
	}
void turnHardLeft()
	{
		motor[RIGHT] = 20;
		motor[LEFT] = -20;
	}
void sonarObsticalCheck(int inType)
	{
	int atCount = 0;
	int whatToDo = random(100);
	int whatToDoNow = random(100);
	switch ( inType ){
		case 1:
			zA = 0;
			stopSensors();
			if ( sonar01 < 20 )
					{
	    			zA = 0;
						if (atCount > 5){break;}else{
						do { turnRight(); } while ( sonar01 < 20 );
	    			//allGo();
	    			//wait1Msec(500);
	    			do { turnLeft(); } while ( ( zA ) < -5 );
  					if ( sonar01 < 20 ) { sonarObsticalCheck(1);}
  					atCount++;
  					}
	    		}	else if ( us_OldResult < 20 )
	    		{
	    			zA = 0;
						if (atCount > 5){break;}else{
		    		do { turnLeft(); } while ( us_OldResult < 20 );
		    		//allGo();
	    			//wait1Msec(500);
	    			do { turnRight(); } while ( ( zA ) > 5 );
	  				if ( us_OldResult < 20 ) { sonarObsticalCheck(1);}
		    		atCount++;
		    		}
  				}
  			runSensors();
				break;
		case 2:
			zA=0;xA=0;yA=0;
			stopSensors();
			if ( sonar01 > us_OldResult ){
						if (atCount > 5){break;}else{
		    			do{ motor[RIGHT] = 15; motor[LEFT] = -15;}while( zA <= 45 );
		    			atCount++;
		    		}
					if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  	}	else if ( sonar01 < us_OldResult ) {
	  				if (atCount > 5){break;}else{
		    			do{ motor[RIGHT] = -15; motor[LEFT] = 15;}while( zA >= -45 );
		    			atCount++;
		    		}
	  			if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  	} else {
	    		if ( whatToDo > 50 ){
						if (atCount > 5){break;}else{
		    			do{ motor[RIGHT] = 15; motor[LEFT] = -15;}while( zA <= 45 );
		    			atCount++;
		    		}
						if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  			}else{
	  				if (atCount > 5){PlaySound(soundException);break;}else{
		    			do{ motor[RIGHT] = -15; motor[LEFT] = 15;}while( zA >= -45 );
		    			atCount++;
		    		}
		    		if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  			}
	    }
	    runSensors();
			break;
		case 3:
			zA=0;xA=0;yA=0;
			stopSensors();
			if ( whatToDoNow > 50 ){
				if (atCount > 5){PlaySound(soundException);break;}else{
						do{ motor[RIGHT] = 15; motor[LEFT] = -15;}while( zA <= 45 );
		    		atCount++;
		    	}
			}else{
				if (atCount > 5){PlaySound(soundException);break;}else{
						do{ motor[RIGHT] = -15; motor[LEFT] = 15;}while( zA >= -45 );
		    		atCount++;
		    	}
			}
			runSensors();
			break;
		}
	}
void allStop()
	{
		allStall();
		sonarObsticalCheck(2);
	}

/*Bluetooth Stuff*/
void SetRawSate()
	{
		nxtDisplayCenteredTextLine(4, "Before RAW");
		setBluetoothRawDataMode();
		while (!bBTRawMode)
			{
				nxtDisplayCenteredTextLine(4, "Inside RAW");
				wait1Msec(1);
			}
		nxtDisplayCenteredTextLine(4, "After RAW");
		eraseDisplay();
	}
void makeConnection()
	{
		string PIN = 1234;
		btConnect(3, "SeeedBTSlave");
		wait1Msec(1000);
		setSessionPIN(PIN);
		nxtDisplayCenteredBigTextLine(2, "Testing!");
		wait1Msec(5000);
		eraseDisplay();
	}
void checkBTLinkConnected()
	{
		if (nBTCurrentStreamIndex >= 0)
			return;
		PlaySound(soundLowBuzz);
		PlaySound(soundLowBuzz);
		eraseDisplay();
		nxtDisplayCenteredTextLine(3, "BT not");
		nxtDisplayCenteredTextLine(4, "Connected");
		wait1Msec(3000);
		StopAllTasks();
	}
void testNXshieldSensors()
	{
		if ( touch01 == 1 )
				{
					allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(750);
					turnHardLeft();
					wait1Msec(500);
					touch01 = 0;
				}
		if ( touch02 == 1 )
				{
					allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(750);
					turnHardRight();
					wait1Msec(500);
					touch02 = 0;
				}
	}
void testSonar()
	{
		if ( ( us_OldResult < 20 ) || ( ( sonar01 < 20 ) && ( sonar01 > 0 ) ) )
	   		{
	  			sonarObsticalCheck(1);
	  		}

	}
