#pragma config(Sensor, S1,     HTMSSUMO,       sensorLightActive)
#pragma config(Sensor, S2,     us_old,         sensorSONAR)
#pragma config(Sensor, S3,     us_new,         sensorSONAR)
#pragma config(Motor,  motorA,          RIGHT,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/mindsensors-sumoeyes.h"
#include "sensorConfig/US_NEW.h"
#include "sensorConfig/US_OLD.h"

void turnRight();
void turnHardRight();
void turnLeft();
void turnHardLeft();
void allStall();
void allGo();
void allBack();
void allStop();
void checkLeft();
void checkRight();

tObstacleZone zone = 0;
int blockLeft = 0;
int blockRight = 0;


task main() {
	// Standard range is set to short range
	eraseDisplay();
	StartTask(USNEW);
	StartTask(USOLD);
  MSSUMOsetShortRange(HTMSSUMO);
  while(true) {
  	blockLeft = 0;
		blockRight = 0;
		zone = MSSUMOreadZone(HTMSSUMO);
    // Check front IR sensor LEFT FRONT RIGHT
    switch (zone) {
      case MSSUMO_FRONT:
      	allStop();
      	break;
      case MSSUMO_LEFT:
      	turnRight();
      	break;
      case MSSUMO_RIGHT:
      	turnLeft();
      	break;
      case MSSUMO_NONE:
      	allGo();
      	break;
    }
    wait1Msec(50);
    // Check left and right sonar sensors for objects
    if ( ( us_NewResult < 10 ) && ( us_OldResult > 10 ) ){
    		turnRight();
    		wait1Msec(200);
    	}	else if ( ( us_NewResult > 10 ) && ( us_OldResult < 10 ) ) {
    		turnLeft();
    		wait1Msec(200);
    	}
  }
}
// Start movement functions
void allGo(){ motor[RIGHT] = 50; motor[LEFT] = 50; }
void allBack(){ motor[RIGHT] = -50; motor[LEFT] = -50; }
void allStall(){ motor[RIGHT] = 0; motor[LEFT] = 0; }
void turnRight(){ motor[RIGHT] = 25; motor[LEFT] = 75; }
void turnLeft(){ motor[RIGHT] = 75; motor[LEFT] = 25; }
void turnHardRight(){ motor[RIGHT] = -50; motor[LEFT] = 50; }
void turnHardLeft(){ motor[RIGHT] = 50; motor[LEFT] = -50; }
// Check for object functions - LEFT AND RIGHT
void checkLeft(){
		zone = MSSUMOreadZone(HTMSSUMO);
		switch ( zone ) {
				case MSSUMO_FRONT: blockLeft = 1; nxtDisplayCenteredBigTextLine(6, "FRONT %d", blockLeft); break;
	      case MSSUMO_LEFT:  blockLeft = 0; nxtDisplayCenteredBigTextLine(6, "LEFT %d", blockLeft);  break;
	      case MSSUMO_RIGHT: blockLeft = 0; nxtDisplayCenteredBigTextLine(6, "RIGHT %d", blockLeft); break;
	      case MSSUMO_NONE:  blockLeft = 0; nxtDisplayCenteredBigTextLine(6, "NONE %d", blockLeft);  break;
		}
		wait1Msec(50);
	}
void checkRight(){
		zone = MSSUMOreadZone(HTMSSUMO);
		switch ( zone ) {
				case MSSUMO_FRONT: blockRight = 1; nxtDisplayCenteredBigTextLine(6, "FRONT %d", blockRight); break;
	      case MSSUMO_LEFT:  blockRight = 0; nxtDisplayCenteredBigTextLine(6, "LEFT %d", blockRight);  break;
	      case MSSUMO_RIGHT: blockRight = 0; nxtDisplayCenteredBigTextLine(6, "RIGHT %d", blockRight); break;
	      case MSSUMO_NONE:  blockRight = 0; nxtDisplayCenteredBigTextLine(6, "NONE %d", blockRight);  break;
		}
		wait1Msec(50);
	}

void allStop(){
	turnHardRight();
	wait1Msec(750);
	allStall();
	checkLeft();
	wait1Msec(200);
	turnHardLeft();
  wait1Msec(1500);
  allStall();
	checkRight();
	wait1Msec(200);
	turnHardRight();
	wait1Msec(750);
	allStall();
	wait1Msec(200);
	 if ( ( blockLeft==1 ) && ( blockRight==1 ) ){
		allBack();
		wait1Msec(500);
		turnHardLeft();
		wait1Msec(1400);
		allStall();
  	wait1Msec(200);
	} else if ( ( blockLeft==0 ) && ( blockRight==1 ) ){
    turnHardRight();
		wait1Msec(250);
		allStall();
  	wait1Msec(200);
	} else if ( ( blockLeft==1 ) && ( blockRight==0 ) ){
  	turnHardLeft();
  	wait1Msec(250);
		allStall();
  	wait1Msec(200);
	} else {
		int turnRan = random(100);
		if (turnRan > 50){
	  	turnHardRight();
			wait1Msec(250);
	    }else{
	      turnHardLeft();
	      wait1Msec(250);
	    }
	}

}




/*
 * $Id: mindsensors-sumoeyes-test1.c 123 2012-11-02 16:35:15Z xander $
 */
