#pragma config(Sensor, S1,     HTMSSUMO,       sensorLightActive)
#pragma config(Sensor, S2,     us_old,         sensorSONAR)
#pragma config(Sensor, S3,     us_new,         sensorSONAR)
#pragma config(Sensor, S4,     DIMU,           sensorI2CCustomFastSkipStates)
#pragma config(Motor,  motorA,          RIGHT,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LEFT,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          CENTER,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/mindsensors-sumoeyes.h"
#include "drivers/dexterind-compass.h"
#include "sensorConfig/US_NEW.h"
#include "sensorConfig/US_OLD.h"
#include "drivers/dexterind-imu.h"
#include "sensorConfig/pollAxies.h"
void runSensors();
void stopSensors();
void turnRight();
void turnHardRight();
void turnLeft();
void turnHardLeft();
void allStall();
void allGo();
void allBack();
void allStop();
void sonarObsticalCheck(int inType);
tObstacleZone zone = 0;
task main() {
	StartTask(USNEW);
	StartTask(USOLD);
	StartTask(pAxies);
	MSSUMOsetShortRange(HTMSSUMO);

	while(true)

  	{
  	runSensors();

  		nxtDisplayCenteredBigTextLine(1, "X: %d", xA);
	  	nxtDisplayCenteredBigTextLine(3, "Y: %d", yA);
	  	nxtDisplayCenteredBigTextLine(5, "Z: %d", zA);
	  	zone = MSSUMOreadZone(HTMSSUMO);
	    switch (zone)
	    	{
		      case MSSUMO_FRONT:
		      	allStop();
		      	break;
		      case MSSUMO_LEFT:
		      	turnRight();
		      	break;
		      case MSSUMO_RIGHT:
		      	turnLeft();
		      	break;
		      case MSSUMO_NONE:
		      	allGo();
		      	break;
	    	}
	   	if ((us_NewResult < 14 ) || ( us_OldResult < 14 ))
	   		{
	  			sonarObsticalCheck(1);
	  		}
	  	if ( xA > 25)
	  		{
		  		allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(1000);
					sonarObsticalCheck(3);
	  		}
	  	if ( yA > 25)
	  		{
		  		allStall();
					wait1Msec(500);
					allBack();
					wait1Msec(1000);
					sonarObsticalCheck(3);
	  		}
  	}
}

void runSensors()
	{
		motor[CENTER} = 40;
	}
void stopSensors()
	{
		motor[CENTER} = 0;
	}
void allGo()
	{
		motor[RIGHT] = 40;
		motor[LEFT] = 39;
	}
void allBack()
	{
		motor[RIGHT] = -40;
		motor[LEFT] = -39;
	}
void allStall()
	{
		motor[RIGHT] = 0;
		motor[LEFT] = 0;
	}
void turnRight()
	{
		motor[RIGHT] = 15;
		motor[LEFT] = 70;
	}
void turnLeft()
	{
		motor[RIGHT] = 70;
		motor[LEFT] = 15;
	}
void turnHardRight()
	{
		motor[RIGHT] = -40;
		motor[LEFT] = 39;
	}
void turnHardLeft()
	{
		motor[RIGHT] = 40;
		motor[LEFT] = -39;
	}
void sonarObsticalCheck(int inType)
	{
	int whatToDo = random(100);
	int whatToDoNow = random(100);
	switch ( inType ){
		case 1:
			zA = 0;
			stopSensors();
			if ( us_NewResult < 14 ){
	    		do { turnRight(); } while ( us_NewResult <= 14 );
	    		do { turnLeft(); } while ( ( zA ) < -3 );
  				if ( us_NewResult <= 14 ) { sonarObsticalCheck(1); };
	    	}	else if ( us_OldResult < 14 ) {
	    		zA = 0;
					do { turnLeft(); } while ( us_OldResult <= 14 );
	    		do { turnRight(); } while ( ( zA ) > 3 );
  				if ( us_OldResult <= 14 ) { sonarObsticalCheck(1); };
	    	}
  			runSensors();
				break;
		case 2:
			zA=0;xA=0;yA=0;
			stopSensors();
			if ( us_NewResult > us_OldResult ){
					do{ motor[RIGHT] = 20; motor[LEFT] = -20; }while( zA <= 55 );
					if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  	}	else if ( us_NewResult < us_OldResult ) {
	  			do{ motor[RIGHT] = -20; motor[LEFT] = 20; }while( zA >= -55 );
	  			if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  	} else {
	    		if ( whatToDo > 50 ){
						do{ motor[RIGHT] = 20; motor[LEFT] = -20; }while( zA <= 55 );
						if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  			}else{
		    		do{ motor[RIGHT] = -20; motor[LEFT] = 20; }while( zA >= -55 );
		    		if ( MSSUMOreadZone(HTMSSUMO) == MSSUMO_FRONT ){sonarObsticalCheck(2);};
	  			}
	    }
	    runSensors();
			break;
		case 3:
			zA=0;xA=0;yA=0;
			stopSensors();
			if ( whatToDoNow > 50 ){
    		do{ motor[RIGHT] = 20; motor[LEFT] = -20; }while( zA <= 55 );
			}else{
    		do{ motor[RIGHT] = -20; motor[LEFT] = 20; }while( zA >= -55 );
			}
			runSensors();
			break;
		}
	}
void allStop()
	{
		allStall();
		sonarObsticalCheck(2);
	}
