#pragma config(Sensor, S1,     Tleft,               sensorTouch)
#pragma config(Sensor, S2,     Tright,              sensorTouch)
#pragma config(Sensor, S3,     TopLight,            sensorCOLORNONE)
#pragma config(Sensor, S4,     sonarSensor,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void touchResponceL();
void touchResponceR();
void lightResponce();

task main{
	int range = 25;
	int turnRange = ( range + 5 );
	int reverseRange = ( turnRange - 20 );
	int turnRan = 0;
	int senTest = 0;
	int senTest2 = 0;
	while(true){
		if (SensorValue[sonarSensor] > range)
			{
				while(SensorValue[sonarSensor] > range )
					{
						senTest = SensorValue[TopLight];
					  senTest2 = SensorValue[sonarSensor];
					  motor[motorB] = 25;
						motor[motorC] = 25;
						//if (SensorValue[Tleft] == 1){
						//	touchResponceL();
						//}
						//if (SensorValue[Tright] == 1){
						//	touchResponceR();
						//}
						//if (SensorValue[TopLight] < 20){
						//  lightResponce();
						//}
						wait1Msec(250);
					}
				motor[motorB] = 0;
				motor[motorC] = 0;
				wait1Msec(250);
		 }
		 else
		 {
				turnRan = random(100);
				while (SensorValue[sonarSensor] <= turnRange )
					{

						if (SensorValue[sonarSensor] < reverseRange ){
							  while	(SensorValue[sonarSensor] < reverseRange )
							    {
						        motor[motorB] = -25;
								    motor[motorC] = -25;
								    //wait1Msec(100);
							    }
						}
						else if (turnRan >= 50)
							{
									while (SensorValue[sonarSensor] <= turnRange )
										{
											motor[motorB] = 25;
											motor[motorC] = -25;
										}
							}
							else
							{
								while (SensorValue[sonarSensor] <= turnRange )
									{
										motor[motorB] = -25;
										motor[motorC] = 25;
									}
							}
				}
				motor[motorB] = 0;
				motor[motorC] = 0;
				wait1Msec(250);
			}
		}
}



void touchResponceL(){
	motor[motorB] = -25;
	motor[motorC] = -25;
	wait1Msec(750);
	motor[motorB] = 25;
	motor[motorC] = -25;
	wait1Msec(1000);
}
void touchResponceR(){
	motor[motorB] = -25;
	motor[motorC] = -25;
	wait1Msec(750);
	motor[motorB] = -25;
	motor[motorC] = 25;
	wait1Msec(1000);
}
void lightResponce(){
	motor[motorB] = -25;
	motor[motorC] = 25;
	wait1Msec(1500);
	motor[motorB] = 25;
	motor[motorC] = 25;
	wait1Msec(1000);
}
