#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S3,     boom,           sensorTouch)
#pragma config(Sensor, S4,     scanHead,       sensorSONAR)
#pragma config(Motor,  motorA,          upDown,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftRight,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void platformUpStep();
void conOutStep();
void conBack();
void takeReading(int lineCount);
void returnToStrat();

int conStepCount = 38;
int liftStepCount = 40;

task main()
{
	bFloatDuringInactiveMotorPWM = false;
	for ( int i = 1; i <= liftStepCount; i++)
		{
		nxtDisplayCenteredBigTextLine(1, "%d", i);
		platformUpStep();
		wait1Msec(500);
		for ( int i = 1; i <= conStepCount; i++)
			{
			conOutStep();
			takeReading(i);
			}
		conBack();
		wait1Msec(500);
		}
	returnToStrat();
}


void returnToStrat()
{
		bFloatDuringInactiveMotorPWM = true;
		nMotorEncoder[motorA] = 0;
		while(nMotorEncoder[motorA] > -500)
			{
				motor[motorA] = -35;
			}
		motor[motorA] = 0;
	return;
}

void platformUpStep()
{
	nMotorEncoder[motorA] = 0;
	while(nMotorEncoder[motorA] < 20)
		{
			motor[motorA] = 50;
		}
	motor[motorA] = 0;
	return;
}

void conOutStep()
{
	nMotorEncoder[motorB] = 0;
	while(nMotorEncoder[motorB] < 5)
		{
			motor[motorB] = 50;
		}
	motor[motorB] = 0;
	return;
}

void conBack()
{

	while (SensorValue[boom] != 1)
		{
			motor[motorB] = -50;
		}
	motor[motorB] = 0;
	wait1Msec(100);
	return
}

void takeReading(int lineCount)
{
	int a = 0;
	int b = 0;
	int c = 0;
	int d = 0;
	int e = 0;
	int f = 0;
	int g = 0;
	int h = 0;
	wait1Msec(100);
	a = SensorValue[scanHead];
	wait1Msec(100);
	b = SensorValue[scanHead];
	wait1Msec(100);
	c = SensorValue[scanHead];
	wait1Msec(100);
	d = SensorValue[scanHead];
	wait1Msec(100);
	e = SensorValue[scanHead];
	wait1Msec(100);
	f = SensorValue[scanHead];
	wait1Msec(100);
	g = SensorValue[scanHead];
	wait1Msec(100);
	h = SensorValue[scanHead];
	int i = (a + b + c + d + e + f + g + h )/8;
	nxtDisplayCenteredBigTextLine(3, "%d", lineCount);
	nxtDisplayCenteredBigTextLine(5, "%d", i);
	writeDebugStream("%d", i);
	if (lineCount < conStepCount)
		{
		writeDebugStream(",");
		} else { writeDebugStreamLine(" + "); }

}
