#pragma config(Sensor, S4,     us_new,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "sensorConfig/US_NEW.h"

task main()
{
	StartTask(USNEW);
	while(true)
		{
			nxtDisplayCenteredBigTextLine(2, "%d", SensorValue[S4]);
			nxtDisplayCenteredBigTextLine(4, "%d", us_NewResult);
			wait1Msec(100);
		}
}
