#pragma config(Sensor, S4,     sonarTest,      sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		eraseDisplay();
		int i = SensorValue[S4];
		if ( i < 22 )
			{
				i = ( i - 5);
			}
			else if ( ( i > 22 ) && ( i < 51 ) )
			{
				i = ( i - 1 );
			}
			else if ( i >= 51 )
			{
				i = ( i - 2 );
			}
		nxtDisplayCenteredTextLine(2, "Sensor: %d",  SensorValue[S4]);
		nxtDisplayCenteredTextLine(4, "Modified: %d",  i);
		wait1Msec(100);
	}
}
